name = "TricubicInterpolations"
uuid = "3623b986-00c8-4e90-a544-3ef5184cc4b4"
authors = ["fgittins <fabiangittins@gmail.com>"]
version = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
